[package]
name = "hardbool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
try = []

[profile.dev]
opt-level = 1

[profile.release]
codegen-units = 2
